// GENERATED FILE - DO NOT EDIT.
// Source: mobile/contracts. Regenerate with `node mobile/tools/generate.mjs`.

package one.zephyr.mobile.contracts

/** One sync entity as frozen by contracts/registries/entity-registry.json. */
data class SyncEntitySpec(
    val type: String,
    val source: String,
    val idField: String,
    val ownerField: String,
    val revisionField: String?,
    val deleteMode: String,
    val dependencyOrder: Int,
    val minimumClientVersion: Int,
    val editableFields: List<String>,
    val secretFields: List<String>,
    val serverAuthorityFields: List<String>,
    val opaquePreserveFields: List<String>,
    val deviceLocalFields: List<String>,
    val capabilities: List<String>,
    val status: String,
) {
    /** Fields One must never name in a fieldMask. */
    val forbiddenMaskFields: List<String> =
        secretFields + serverAuthorityFields + opaquePreserveFields + deviceLocalFields
}

object EntityRegistry {
    const val VERSION: Int = 1
    const val SOURCE_COMMIT: String = "8dd5b98"

    val classification: List<String> = listOf("editableSync", "opaquePreserve", "deviceLocal", "serverOnly")
    val excludedEditableScopes: List<String> = listOf("accountSecurity", "smtp", "captcha", "ipPolicy", "beian", "customCssJs", "multiUserAdmin")

    val entities: List<SyncEntitySpec> = listOf(
        SyncEntitySpec(
            type = "connection",
            source = "ResourceService/storage.js connections",
            idField = "id",
            ownerField = "ownerUserId",
            revisionField = "revision",
            deleteMode = "tombstone",
            dependencyOrder = 40,
            minimumClientVersion = 1,
            editableFields = listOf("name", "host", "port", "protocol", "username", "remark", "tags", "connectionMode", "proxyId", "jumpHostId", "jumpHostIds", "sshKeyId", "rdpSoundMode", "rdpClipboard", "rdpMicrophone", "rdpCamera", "rdpStorage", "rdpLocation", "rdpResolution", "rdpQuality", "rdpFps", "rdpTouchMode", "rdpTouchSensitivity", "rdpDomain", "encoding"),
            secretFields = listOf("password", "privateKey"),
            serverAuthorityFields = listOf("ownerUserId", "createdByUserId", "revision", "createdAt", "updatedAt", "lastConnectedAt", "visibility"),
            opaquePreserveFields = listOf("rdpPipeline"),
            deviceLocalFields = listOf("ephemeral"),
            capabilities = listOf("discover", "view", "use", "observe", "control", "execute", "fileRead", "fileWrite", "edit", "share", "delete", "revealSecret"),
            status = "implemented-canonical-service-revision-tombstone-atomic-change-feed-secret-safe-projection",
        ),
        SyncEntitySpec(
            type = "proxy",
            source = "ResourceService/storage.js proxies",
            idField = "id",
            ownerField = "ownerUserId",
            revisionField = "revision",
            deleteMode = "tombstone",
            dependencyOrder = 10,
            minimumClientVersion = 1,
            editableFields = listOf("name", "host", "port", "type", "username"),
            secretFields = listOf("password"),
            serverAuthorityFields = listOf("ownerUserId", "revision", "createdAt", "updatedAt", "visibility"),
            opaquePreserveFields = emptyList(),
            deviceLocalFields = emptyList(),
            capabilities = listOf("discover", "view", "use", "edit", "share", "delete", "revealSecret"),
            status = "implemented-canonical-service-revision-tombstone-atomic-change-feed-secret-safe-projection",
        ),
        SyncEntitySpec(
            type = "sshKey",
            source = "ResourceService/storage.js ssh_keys",
            idField = "id",
            ownerField = "ownerUserId",
            revisionField = "revision",
            deleteMode = "tombstone",
            dependencyOrder = 10,
            minimumClientVersion = 1,
            editableFields = listOf("name", "remark"),
            secretFields = listOf("privateKey", "passphrase"),
            serverAuthorityFields = listOf("ownerUserId", "revision", "createdAt", "updatedAt", "visibility"),
            opaquePreserveFields = emptyList(),
            deviceLocalFields = emptyList(),
            capabilities = listOf("discover", "view", "use", "edit", "share", "delete", "revealSecret"),
            status = "implemented-canonical-service-revision-tombstone-atomic-change-feed-secret-safe-projection",
        ),
        SyncEntitySpec(
            type = "jumpHost",
            source = "ResourceService/storage.js jump_hosts",
            idField = "id",
            ownerField = "ownerUserId",
            revisionField = "revision",
            deleteMode = "tombstone",
            dependencyOrder = 20,
            minimumClientVersion = 1,
            editableFields = listOf("name", "connectionId"),
            secretFields = emptyList(),
            serverAuthorityFields = listOf("ownerUserId", "revision", "createdAt", "updatedAt", "visibility"),
            opaquePreserveFields = emptyList(),
            deviceLocalFields = emptyList(),
            capabilities = listOf("discover", "view", "use", "edit", "share", "delete"),
            status = "implemented-canonical-service-revision-tombstone-atomic-change-feed-secret-safe-projection",
        ),
        SyncEntitySpec(
            type = "note",
            source = "NotesService/storage.js notes",
            idField = "noteId",
            ownerField = "ownerUserId",
            revisionField = "revision",
            deleteMode = "soft-delete-then-tombstone",
            dependencyOrder = 50,
            minimumClientVersion = 1,
            editableFields = listOf("title", "content", "groupPath", "tags", "linkedConnectionIds", "sortOrder", "shareWithUsers", "shareWithAdmins", "allowAiRead", "allowAiWrite", "visibility"),
            secretFields = emptyList(),
            serverAuthorityFields = listOf("ownerUserId", "revision", "createdAt", "updatedAt", "deletedAt"),
            opaquePreserveFields = listOf("allowAi"),
            deviceLocalFields = emptyList(),
            capabilities = emptyList(),
            status = "implemented-canonical-service-revision-tombstone-atomic-change-feed-secret-safe-projection",
        ),
        SyncEntitySpec(
            type = "snippet",
            source = "SnippetService/snippets",
            idField = "id",
            ownerField = "ownerUserId",
            revisionField = "revision",
            deleteMode = "tombstone",
            dependencyOrder = 50,
            minimumClientVersion = 1,
            editableFields = listOf("name", "command", "group", "autoRun"),
            secretFields = emptyList(),
            serverAuthorityFields = listOf("ownerUserId", "revision", "createdAt", "updatedAt"),
            opaquePreserveFields = emptyList(),
            deviceLocalFields = emptyList(),
            capabilities = emptyList(),
            status = "implemented-canonical-service-revision-tombstone-atomic-change-feed-secret-safe-projection",
        ),
        SyncEntitySpec(
            type = "aiProvider",
            source = "AiProviderService/ai_providers",
            idField = "id",
            ownerField = "ownerUserId",
            revisionField = "revision",
            deleteMode = "tombstone",
            dependencyOrder = 10,
            minimumClientVersion = 1,
            editableFields = listOf("name", "type", "baseUrl", "defaultModel", "models", "config", "visibility", "shareWithUsers", "shareWithAdmins", "sharedUserIds", "enabled"),
            secretFields = listOf("apiKey"),
            serverAuthorityFields = listOf("ownerUserId", "revision", "createdAt", "updatedAt"),
            opaquePreserveFields = emptyList(),
            deviceLocalFields = emptyList(),
            capabilities = emptyList(),
            status = "implemented-canonical-service-revision-tombstone-atomic-change-feed-secret-safe-projection",
        ),
        SyncEntitySpec(
            type = "aiMemory",
            source = "AiKnowledgeService/ai_knowledge_entities",
            idField = "id",
            ownerField = "ownerUserId",
            revisionField = "revision",
            deleteMode = "tombstone",
            dependencyOrder = 50,
            minimumClientVersion = 1,
            editableFields = listOf("title", "content", "scope", "project", "projects", "tags", "connectionIds"),
            secretFields = emptyList(),
            serverAuthorityFields = listOf("ownerUserId", "revision", "createdAt", "updatedAt"),
            opaquePreserveFields = emptyList(),
            deviceLocalFields = emptyList(),
            capabilities = emptyList(),
            status = "implemented-canonical-service-revision-tombstone-atomic-change-feed-secret-safe-projection",
        ),
        SyncEntitySpec(
            type = "aiSkill",
            source = "AiKnowledgeService/ai_knowledge_entities",
            idField = "id",
            ownerField = "ownerUserId",
            revisionField = "revision",
            deleteMode = "tombstone",
            dependencyOrder = 50,
            minimumClientVersion = 1,
            editableFields = listOf("name", "description", "prompt", "enabled"),
            secretFields = emptyList(),
            serverAuthorityFields = listOf("ownerUserId", "revision", "createdAt", "updatedAt"),
            opaquePreserveFields = emptyList(),
            deviceLocalFields = emptyList(),
            capabilities = emptyList(),
            status = "implemented-canonical-service-revision-tombstone-atomic-change-feed-secret-safe-projection",
        ),
        SyncEntitySpec(
            type = "aiEnv",
            source = "AiKnowledgeService/ai_knowledge_entities + ai_knowledge_env_secrets",
            idField = "id",
            ownerField = "ownerUserId",
            revisionField = "revision",
            deleteMode = "tombstone",
            dependencyOrder = 20,
            minimumClientVersion = 1,
            editableFields = listOf("name", "enabled", "visibleToAi"),
            secretFields = listOf("value"),
            serverAuthorityFields = listOf("ownerUserId", "revision", "createdAt", "updatedAt"),
            opaquePreserveFields = emptyList(),
            deviceLocalFields = emptyList(),
            capabilities = emptyList(),
            status = "implemented-canonical-service-revision-tombstone-atomic-change-feed-secret-safe-projection",
        ),
        SyncEntitySpec(
            type = "aiConversation",
            source = "AiHistoryService/ai_conversations",
            idField = "id",
            ownerField = "ownerUserId",
            revisionField = "revision",
            deleteMode = "tombstone",
            dependencyOrder = 50,
            minimumClientVersion = 1,
            editableFields = listOf("title", "providerId", "model", "archived"),
            secretFields = emptyList(),
            serverAuthorityFields = listOf("ownerUserId", "revision", "createdAt", "updatedAt"),
            opaquePreserveFields = listOf("runtimeMetadata"),
            deviceLocalFields = listOf("activeRunId"),
            capabilities = emptyList(),
            status = "implemented-canonical-service-revision-tombstone-atomic-change-feed-secret-safe-projection",
        ),
        SyncEntitySpec(
            type = "aiMessage",
            source = "AiHistoryService/ai_messages",
            idField = "id",
            ownerField = "ownerUserId",
            revisionField = "revision",
            deleteMode = "tombstone",
            dependencyOrder = 60,
            minimumClientVersion = 1,
            editableFields = listOf("conversationId", "role", "content", "attachments"),
            secretFields = emptyList(),
            serverAuthorityFields = listOf("ownerUserId", "revision", "createdAt", "updatedAt"),
            opaquePreserveFields = listOf("toolEvents", "usage"),
            deviceLocalFields = listOf("streamState"),
            capabilities = emptyList(),
            status = "implemented-canonical-service-revision-tombstone-atomic-change-feed-secret-safe-projection",
        ),
        SyncEntitySpec(
            type = "oneUserSettings",
            source = "PersonalSettingsSectionService + user_setting_sections/user_settings",
            idField = "sectionKey",
            ownerField = "userId",
            revisionField = "revision",
            deleteMode = "reset-to-default",
            dependencyOrder = 50,
            minimumClientVersion = 1,
            editableFields = listOf("appearance.theme", "appearance.autoThemeEnabled", "appearance.colorScheme", "appearance.customThemeMode", "appearance.customColors", "appearance.terminalBackground", "appearance.terminalFontColor", "appearance.terminalFontColors", "appearance.rdp", "terminal.maxWindows", "terminal.minimizedKeepAlive", "terminal.smartbarOrder", "terminal.shortcutPlatform", "terminal.allowLigatures", "notes.enabled", "notes.editorMode", "notes.fontSize", "workspace.defaultView", "workspace.sessionPersistence", "ai.panelLayout", "ai.assistantName"),
            secretFields = emptyList(),
            serverAuthorityFields = listOf("userId", "revision", "updatedAt"),
            opaquePreserveFields = listOf("appearance.customCss", "mail.notifyLogin"),
            deviceLocalFields = emptyList(),
            capabilities = emptyList(),
            status = "implemented-canonical-service-revision-reset-atomic-change-feed-secret-safe-projection",
        ),
        SyncEntitySpec(
            type = "serverSettings",
            source = "CanonicalServerSettingsService/storage.js settings",
            idField = "sectionKey",
            ownerField = "serverId",
            revisionField = "revision",
            deleteMode = "reset-to-default",
            dependencyOrder = 50,
            minimumClientVersion = 1,
            editableFields = listOf("appearance", "notes", "ai.enabled", "ai.permissions", "ai.context", "ai.memory.enabled", "ai.memory.maxItems"),
            secretFields = emptyList(),
            serverAuthorityFields = listOf("serverId", "revision", "updatedAt", "requiredRole"),
            opaquePreserveFields = listOf("security", "mail", "captcha", "beian", "appearance.customCss", "appearance.customJs"),
            deviceLocalFields = emptyList(),
            capabilities = emptyList(),
            status = "blocked-owner-scope-change-feed-partition-mismatch",
        ),
        SyncEntitySpec(
            type = "backupMetadata",
            source = "/api/data/export + /api/data/import",
            idField = "backupId",
            ownerField = "serverId",
            revisionField = "revision",
            deleteMode = "job-retention",
            dependencyOrder = 70,
            minimumClientVersion = 1,
            editableFields = listOf("label", "retentionHint"),
            secretFields = emptyList(),
            serverAuthorityFields = listOf("serverId", "revision", "createdAt", "size", "sha256", "appVersion", "encryptionAlgorithm", "jobStatus"),
            opaquePreserveFields = emptyList(),
            deviceLocalFields = listOf("localDownloadUri"),
            capabilities = emptyList(),
            status = "blocked-no-durable-job-metadata-layer",
        ),
        SyncEntitySpec(
            type = "activityEvent",
            source = "CanonicalActivityEventService/storage.js activities",
            idField = "id",
            ownerField = "userId",
            revisionField = null,
            deleteMode = "append-only",
            dependencyOrder = 80,
            minimumClientVersion = 1,
            editableFields = emptyList(),
            secretFields = emptyList(),
            serverAuthorityFields = listOf("id", "userId", "time", "message", "type", "sourceIp", "durationMs", "category", "outcome", "actor", "protocol", "target", "connectionId"),
            opaquePreserveFields = emptyList(),
            deviceLocalFields = emptyList(),
            capabilities = emptyList(),
            status = "implemented-read-only-canonical-service-append-only-atomic-change-feed-secret-safe-projection",
        ),
        SyncEntitySpec(
            type = "resourceAcl",
            source = "ResourceAclMetadataService/resource_acl",
            idField = "grantKey",
            ownerField = "resourceOwnerUserId",
            revisionField = "revision",
            deleteMode = "revocation-tombstone",
            dependencyOrder = 30,
            minimumClientVersion = 1,
            editableFields = listOf("capabilities", "expiresAt"),
            secretFields = emptyList(),
            serverAuthorityFields = listOf("subjectType", "subjectId", "grantedByUserId", "createdAt", "revokedAt", "revision"),
            opaquePreserveFields = emptyList(),
            deviceLocalFields = emptyList(),
            capabilities = listOf("discover", "view", "use", "observe", "control", "execute", "fileRead", "fileWrite", "edit", "share", "delete", "revealSecret", "administer"),
            status = "implemented-canonical-service-revision-revocation-tombstone-atomic-change-feed-secret-safe-projection",
        ),
        SyncEntitySpec(
            type = "clientToken",
            source = "AgentTokenStore/encrypted_client_tokens",
            idField = "id",
            ownerField = "ownerUserId",
            revisionField = "revision",
            deleteMode = "tombstone",
            dependencyOrder = 0,
            minimumClientVersion = 1,
            editableFields = listOf("name"),
            secretFields = listOf("token"),
            serverAuthorityFields = listOf("ownerUserId", "revision", "createdAt", "updatedAt", "lastUsedAt"),
            opaquePreserveFields = emptyList(),
            deviceLocalFields = emptyList(),
            capabilities = emptyList(),
            status = "implemented-canonical-service-revision-tombstone-atomic-change-feed-secret-safe-projection",
        ),
        SyncEntitySpec(
            type = "workspaceState",
            source = "WorkspacePortableSyncService + workspaces/workspace_portable_identities",
            idField = "workspaceId",
            ownerField = "userId",
            revisionField = "revision",
            deleteMode = "tombstone",
            dependencyOrder = 80,
            minimumClientVersion = 1,
            editableFields = listOf("name", "state"),
            secretFields = emptyList(),
            serverAuthorityFields = listOf("userId", "revision", "updatedAt"),
            opaquePreserveFields = emptyList(),
            deviceLocalFields = listOf("clientId"),
            capabilities = emptyList(),
            status = "implemented-canonical-service-revision-tombstone-atomic-change-feed-secret-safe-projection",
        ),
        SyncEntitySpec(
            type = "fileSyncConfig",
            source = "FileSyncConfigService + mobile_devices/one_clients",
            idField = "clientId",
            ownerField = "ownerUserId",
            revisionField = "syncRevision",
            deleteMode = "revoke",
            dependencyOrder = 0,
            minimumClientVersion = 1,
            editableFields = listOf("deviceName", "enabled", "automaticEnabled", "syncIntervalSec"),
            secretFields = emptyList(),
            serverAuthorityFields = listOf("ownerUserId", "syncRevision", "tokenId", "platform", "appVersion", "lastSyncAt", "lastSeenAt", "createdAt", "revokedAt"),
            opaquePreserveFields = emptyList(),
            deviceLocalFields = listOf("networkPolicy", "lastLocalAttemptAt", "localError"),
            capabilities = emptyList(),
            status = "implemented-canonical-service-revision-revoke-atomic-change-feed-secret-safe-projection",
        ),
    )

    val byType: Map<String, SyncEntitySpec> = entities.associateBy { it.type }

    /** Push topology order: dependencies first, ties broken by type name. */
    val pushOrder: List<String> = listOf("clientToken", "fileSyncConfig", "aiProvider", "proxy", "sshKey", "aiEnv", "jumpHost", "resourceAcl", "connection", "aiConversation", "aiMemory", "aiSkill", "note", "oneUserSettings", "serverSettings", "snippet", "aiMessage", "backupMetadata", "activityEvent", "workspaceState")

    fun require(type: String): SyncEntitySpec =
        byType[type] ?: throw IllegalArgumentException("unknown entityType " + type)

    fun isEditableScope(scope: String): Boolean = !excludedEditableScopes.contains(scope)
}
