// Generated by tool/set_version.py.
//
// `version` is the semantic version baked at compile time (from release tag
// agent-v1.0.12 → 1.0.12). UI footer shows `tag` = "v" + version.
class AgentVersion {
  static const String version = String.fromEnvironment(
    'ZEPHYR_AGENT_VERSION',
    defaultValue: '1.0.12',
  );
  static const int buildNumber = int.fromEnvironment(
    'ZEPHYR_AGENT_BUILD_NUMBER',
    defaultValue: 10012,
  );

  /// Full build id for diagnostics (semver+code).
  static String get display => '$version+$buildNumber';

  /// User-facing tag, e.g. "v1.0.12" — matches the suffix of release tag agent-v*.
  static String get tag {
    final v = version.trim();
    if (v.isEmpty) return 'v0.0.0';
    return v.startsWith('v') ? v : 'v$v';
  }
}
