// Generated by tool/set_version.py.
class AgentVersion {
  static const String version = String.fromEnvironment('ZEPHYR_AGENT_VERSION', defaultValue: '1.0.0');
  static const int buildNumber = int.fromEnvironment('ZEPHYR_AGENT_BUILD_NUMBER', defaultValue: 1);
  static String get display => '$version+$buildNumber';
}
