#!/usr/bin/env python3
from __future__ import annotations

import os
import re
import sys
from pathlib import Path

SEMVER_RE = re.compile(r"(\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?)")


def parse_version(raw: str | None) -> str:
    value = (raw or os.environ.get("ZEPHYR_AGENT_VERSION") or "").strip()
    if not value:
        pubspec = Path("pubspec.yaml")
        if pubspec.exists():
            for line in pubspec.read_text(encoding="utf-8").splitlines():
                if line.startswith("version:"):
                    value = line.split(":", 1)[1].strip().split("+", 1)[0]
                    break
    match = SEMVER_RE.search(value)
    if not match:
        raise SystemExit(f"Cannot derive semantic version from: {value!r}")
    return match.group(1).split("+", 1)[0]


def version_code(version: str, fallback: str | None = None) -> str:
    if fallback and fallback.strip().isdigit():
        return fallback.strip()
    nums = [int(x) for x in re.findall(r"\d+", version)[:3]]
    while len(nums) < 3:
        nums.append(0)
    major, minor, patch = nums[:3]
    return str(major * 10000 + minor * 100 + patch)


def main() -> None:
    raw = sys.argv[1] if len(sys.argv) > 1 else None
    version = parse_version(raw)
    code = version_code(version, os.environ.get("ZEPHYR_AGENT_VERSION_CODE") or os.environ.get("GITHUB_RUN_NUMBER"))
    dart = Path("lib/app/agent_version.dart")
    dart.parent.mkdir(parents=True, exist_ok=True)
    dart.write_text(
        "// Generated by tool/set_version.py.\n"
        "class AgentVersion {\n"
        f"  static const String version = String.fromEnvironment('ZEPHYR_AGENT_VERSION', defaultValue: '{version}');\n"
        f"  static const int buildNumber = int.fromEnvironment('ZEPHYR_AGENT_BUILD_NUMBER', defaultValue: {code});\n"
        "  static String get display => '$version+$buildNumber';\n"
        "}\n",
        encoding="utf-8",
    )
    env_file = os.environ.get("GITHUB_ENV")
    if env_file:
        with open(env_file, "a", encoding="utf-8") as f:
            f.write(f"ZEPHYR_AGENT_VERSION_NAME={version}\n")
            f.write(f"ZEPHYR_AGENT_VERSION_CODE={code}\n")
    print(f"ZEPHYR_AGENT_VERSION_NAME={version}")
    print(f"ZEPHYR_AGENT_VERSION_CODE={code}")


if __name__ == "__main__":
    main()
