import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const mobileRoot = path.resolve(here, '..');
const repoRoot = path.resolve(mobileRoot, '..', '..');
const exporter = path.join(here, 'export-production-sync-fixtures.mjs');
const fixturePath = path.join(
  mobileRoot,
  'android/core-network/src/test/resources/production-sync-wire.json',
);

function stableFixture(raw) {
  const fixture = JSON.parse(raw);
  fixture.bootstrap.bootstrapId = 'bs-production-fixture';
  return JSON.stringify(fixture, null, 2) + '\n';
}

test('Android production sync fixture is generated by the real Node response path', () => {
  const generated = execFileSync(process.execPath, [exporter], {
    cwd: repoRoot,
    encoding: 'utf8',
    env: process.env,
  });
  const committed = fs.readFileSync(fixturePath, 'utf8');

  assert.equal(committed, stableFixture(generated));
});

test('fixture covers capabilities bootstrap and changes parser boundaries', () => {
  const fixture = JSON.parse(fs.readFileSync(fixturePath, 'utf8'));

  assert.equal(fixture.capabilities.ok, true);
  assert.equal(Object.hasOwn(fixture.capabilities, 'serverEncryption'), true);
  assert.equal(fixture.bootstrap.ok, true);
  assert.equal(fixture.bootstrap.complete, true);
  assert.equal(fixture.bootstrap.nextPageToken, null);
  assert.ok(fixture.bootstrap.entities.length > 0);
  assert.equal(fixture.changes.ok, true);
  assert.ok(fixture.changes.changes.length > 0);
});
